### ISSUE TITLE
syntax error when running newest version 1.1.0

### ISSUE THREAD

**Issue by saigrain** [natashabatalha/PandExo#20]
I just upgraded to the new version following @natashabatalha 's announcement that it should be more efficient for bright targets. When I try to run a calculation I get a syntax error:

Traceback (most recent call last):
  File "./simulate_obs", line 67, in <module>
    res = do_sim(args.model, inst, **kwarg_dict)
  File "./simulate_obs", line 34, in do_sim
    res = jdi.run_pandexo(exo_dict,[inst])    
  File "/Users/aigrain/anaconda/lib/python2.7/site-packages/pandexo/engine/justdoit.py", line 269, in run_pandexo
    results =wrapper({"pandeia_input": inst_dict , "pandexo_input":exo})
  File "/Users/aigrain/anaconda/lib/python2.7/site-packages/pandexo/engine/pandexo.py", line 32, in wrapper
    from .jwst import compute_full_sim
  File "/Users/aigrain/anaconda/lib/python2.7/site-packages/pandexo/engine/jwst.py", line 156
    print("Finished Duty Cycle Calc", print(m["maxexptime_per_int"]))

Easily fixed (done it on my local version) but I thought I'd bring it up

**Comment by natashabatalha** [comment]
Got it! [https://github.com/natashabatalha/PandExo/blob/master/pandexo/engine/jwst.py#L156](url)
