### ISSUE TITLE
Failure with NoneType data in parameter list

### ISSUE THREAD

**Issue by flahuis** [natashabatalha/PandExo#25]
(pandexo) mac-525:PandExo freddy$ python run_test.py 
Starting TEST run
Running Single Case for: NIRSpec G140H
Traceback (most recent call last):
  File "run_test.py", line 30, in <module>
    jdi.run_pandexo(exo_dict, ['NIRSpec G140H'], save_file=False)
  File "/Users/freddy/ownCloud/Software/GitHub/PandExo/pandexo/engine/justdoit.py", line 269, in run_pandexo
    results =wrapper({"pandeia_input": inst_dict , "pandexo_input":exo})
  File "/Users/freddy/ownCloud/Software/GitHub/PandExo/pandexo/engine/pandexo.py", line 33, in wrapper
    return compute_full_sim(dictinput)
  File "/Users/freddy/ownCloud/Software/GitHub/PandExo/pandexo/engine/jwst.py", line 83, in compute_full_sim
    i = InstrumentFactory(config=conf_temp)
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/site-packages/pandeia/engine/instrument_factory.py", line 50, in InstrumentFactory
    cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/site-packages/pandeia/engine/jwst.py", line 62, in __init__
    JWSTInstrument.__init__(self, mode=mode, config=config, webapp=webapp, **kwargs)
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/site-packages/pandeia/engine/jwst.py", line 32, in __init__
    telescope = JWST()
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/site-packages/pandeia/engine/config.py", line 46, in __init__
    all_config = merge_data(self._get_config(), config, dict(**kwargs))
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/site-packages/pandeia/engine/telescope.py", line 33, in _get_config
    self.ref_dir = os.path.join(default_refdata_directory, self.tel_name, "telescope")
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/freddy/anaconda3/envs/pandexo/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by natashabatalha** [comment]
Can you check that you are running Pandeia 1.3 and have the 1.3 reference data?
