### ISSUE TITLE
RuntimeError: unsupported data type

### ISSUE THREAD

**Issue by astrojt** [natashabatalha/PandExo#31]
Hi Natasha, I've been trying to install pandexo using the instructions on the github and it doesn't seem to be working. I've run into this error:
Starting TEST run
Running Single Case for: NIRSpec G140H
Optimization Reqested: Computing Duty Cycle
Traceback (most recent call last):
  File "run_test.py", line 30, in <module>
    jdi.run_pandexo(exo_dict, ['NIRSpec G140H'], save_file=False)
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/justdoit.py", line 326, in run_pandexo
    results =wrapper({"pandeia_input": inst_dict , "pandexo_input":exo})
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/pandexo.py", line 33, in wrapper
    return compute_full_sim(dictinput)
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/jwst.py", line 154, in compute_full_sim
    m = {"maxexptime_per_int":compute_maxexptime_per_int(pandeia_input, sat_level) , 
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/jwst.py", line 341, in compute_maxexptime_per_int
    report = perform_calculation(pandeia_input, dict_report=False)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/pandeia/engine/perform_calculation.py", line 39, in perform_calculation
    report = calculate_sn(calc_input, webapp=webapp)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/pandeia/engine/etc3D.py", line 1383, in calculate_sn
    my_detector_signal = DetectorSignal(o, calc_config=calc_config, webapp=webapp, order=None)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/pandeia/engine/etc3D.py", line 118, in __init__
    slice_rate = self.all_rates(flux_cube, add_extended_background=False)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/pandeia/engine/etc3D.py", line 392, in all_rates
    fp_pix_rate_ipc = self.ipc_convolve(fp_pix_rate, kernel)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/pandeia/engine/etc3D.py", line 719, in ipc_convolve
    fp_pix_ipc = sg.fftconvolve(rate, kernel, mode='same')
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 542, in fftconvolve
    ret = _freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 383, in _freq_domain_conv
    sp2 = fft(in2, fshape, axes=axes)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/scipy/fft/_backend.py", line 23, in __ua_function__
    return fn(*args, **kwargs)
  File "/home/jaketaylor/anaconda3/envs/pandexo2/lib/python3.7/site-packages/scipy/fft/_pocketfft/basic.py", line 186, in r2cn
    return pfft.r2c(tmp, axes, forward, norm, None, workers)
RuntimeError: unsupported data type

I'm using pandeia_data-1.4. I've also tried pandeia_data-1.5 and that also didn't work. I upgraded pandeia.engine to version 1.5 but this isn't compatible with pandexo.engine version 1.4 and so that falls over too with this error:
Starting TEST run
Running Single Case for: NIRSpec G140H
Traceback (most recent call last):
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/jwst.py", line 77, in compute_full_sim
    i = InstrumentFactory(config=conf)
  File "/home/jaketaylor/anaconda3/envs/pandexo3/lib/python3.7/site-packages/pandeia/engine/instrument_factory.py", line 50, in InstrumentFactory
    cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
  File "/home/jaketaylor/anaconda3/envs/pandexo3/lib/python3.7/site-packages/pandeia/engine/jwst.py", line 59, in __init__
    self.detector_readout_pattern = config['detector']['readout_pattern']
KeyError: 'readout_pattern'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_test.py", line 30, in <module>
    jdi.run_pandexo(exo_dict, ['NIRSpec G140H'], save_file=False)
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/justdoit.py", line 326, in run_pandexo
    results =wrapper({"pandeia_input": inst_dict , "pandexo_input":exo})
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/pandexo.py", line 33, in wrapper
    return compute_full_sim(dictinput)
  File "/network/group/aopp/planetary/PGJI007_TAYLOR_EXOSIM/pandexo/pandexo/engine/jwst.py", line 83, in compute_full_sim
    i = InstrumentFactory(config=conf_temp)
  File "/home/jaketaylor/anaconda3/envs/pandexo3/lib/python3.7/site-packages/pandeia/engine/instrument_factory.py", line 50, in InstrumentFactory
    cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
  File "/home/jaketaylor/anaconda3/envs/pandexo3/lib/python3.7/site-packages/pandeia/engine/jwst.py", line 59, in __init__
    self.detector_readout_pattern = config['detector']['readout_pattern']
KeyError: 'readout_pattern'

I was wondering if you had any ideas on how to fix this?
Thanks!

**Comment by astrojt** [comment]
Thanks to Aarynn Carter the second issue is due to an upgrade in pandeia, it now reads "readout_pattern" as "readmode". Changing this solved that issue, however I now get the unsupported data type with pandeia 1.5 as well.

**Comment by natashabatalha** [comment]
For people wondering about Pandeia 1.5.1, I've upgraded PandExo 1.5.1 in the dev branch, but we are still working on a couple more things before we do the full 1.5.1 release! Pandeia 1.5.1 will not change your simulations. Stick to 1.4 until the new release, or checkout the dev branch. Whatever you do, do **not** use PandExo 1.4 with Pandeia 1.5+.

**Comment by pcubillos** [comment]
Hi @astrojt 
I ran into the same 'unsupported data type' issue, which seems to come from scipy. I downgraded to:
pip install scipy==1.3.3
and then the run_test.py script worked.
