### ISSUE TITLE
run_test.py issue: RuntimeError: unsupported data type

### ISSUE THREAD

**Issue by wj198414** [natashabatalha/PandExo#41]
Hi, 

I am new and ran into the following issue when running run_test.py. Any ideas?

(pandexo) dapangs-MacBook-Air:Downloads dapang182$ python run_test.py 
Starting TEST run
Running Single Case for: NIRSpec G140H
Optimization Reqested: Computing Duty Cycle
Traceback (most recent call last):
  File "run_test.py", line 30, in <module>
    jdi.run_pandexo(exo_dict, ['NIRSpec G140H'], save_file=False)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandexo/engine/justdoit.py", line 326, in run_pandexo
    results =wrapper({"pandeia_input": inst_dict , "pandexo_input":exo})
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandexo/engine/pandexo.py", line 33, in wrapper
    return compute_full_sim(dictinput)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandexo/engine/jwst.py", line 154, in compute_full_sim
    m = {"maxexptime_per_int":compute_maxexptime_per_int(pandeia_input, sat_level) , 
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandexo/engine/jwst.py", line 341, in compute_maxexptime_per_int
    report = perform_calculation(pandeia_input, dict_report=False)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandeia/engine/perform_calculation.py", line 39, in perform_calculation
    report = calculate_sn(calc_input, webapp=webapp)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandeia/engine/etc3D.py", line 1383, in calculate_sn
    my_detector_signal = DetectorSignal(o, calc_config=calc_config, webapp=webapp, order=None)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandeia/engine/etc3D.py", line 118, in __init__
    slice_rate = self.all_rates(flux_cube, add_extended_background=False)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandeia/engine/etc3D.py", line 392, in all_rates
    fp_pix_rate_ipc = self.ipc_convolve(fp_pix_rate, kernel)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/pandeia/engine/etc3D.py", line 719, in ipc_convolve
    fp_pix_ipc = sg.fftconvolve(rate, kernel, mode='same')
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 542, in fftconvolve
    ret = _freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 383, in _freq_domain_conv
    sp2 = fft(in2, fshape, axes=axes)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/scipy/fft/_backend.py", line 23, in __ua_function__
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/anaconda/envs/pandexo/lib/python3.6/site-packages/scipy/fft/_pocketfft/basic.py", line 186, in r2cn
    return pfft.r2c(tmp, axes, forward, norm, None, workers)
RuntimeError: unsupported data type

Thanks,
Ji

**Comment by natashabatalha** [comment]
This was fixed in the `dev` branch by forcing `pip install scipy==1.3.1`

**Comment by wj198414** [comment]
Done! Thanks.

Ji

Natasha Batalha <notifications@github.com> 于2020年3月12日周四 下午10:10写道：
